### ISSUE TITLE
如何得到每个git commit的代码变化

### ISSUE THREAD

**Issue by CloudHuang** [tiimgreen/github-cheat-sheet#123]
> 如何得到每个git commit的代码变化

记得有一个这样的tool，但是忘了叫什么了，有没有人知道并把这个列出来？

**Comment by wangzuo** [comment]
`git log -p`?

**Comment by Huntter** [comment]
@wangzuo 

这个是命令行的，我记得有个工具，将LOG输出成PPT的。
