### ISSUE TITLE
Reademe.md利用chrome转成的pdf，目录链接不能跳转

### ISSUE THREAD

**Issue by spartawhy117** [tiimgreen/github-cheat-sheet#138]
如题，利用readme.md生成的网页页面利用chrome自带的打印公共转存为pdf，目录连接处的所有目录条目都不能跳转，但是直接在github的网页端可以正常跳转，不知道其中的原因，求解答。

**Comment by tonyxue** [comment]
因为目录的实现方式使用的是html的id在元素之间跳转。你用的功能是打印，这个相对位置当然是没有被打印抓取下来的，毕竟打印下来的东西都是静止的，不是交互的。

**Comment by spartawhy117** [comment]
![image](https://cloud.githubusercontent.com/assets/9450028/8397270/b92034fe-1df8-11e5-9ab0-b95516470fad.png)
但是这种情况下的目录打印出来时是能够跳转的，我发现不同主要在head的书写形式上，如果采用markdown里的`#`来完成的话是不能跳转的，但是采用`<h2 id=xxx>概述</h2>`这种形式的话，打印出来的能够跳转

**Comment by tiimgreen** [comment]
@tonyxue could you provide a translation of this issue?

**Comment by tonyxue** [comment]
Sure.

@tiimgreen : 
@spartawhy117 is trying to covert the ```Readme.md``` file of this repo to pdf file using Chrome's print function. However, the links of the table of contents in the converted pdf are not working.

So in the second reply, he stated that if converting a markdown file with links written in html format, the links would work in the converted pdf. But not when using the markdown syntax to make a link (Using ```#something```).

**Comment by spartawhy117** [comment]
@tiimgreen
 
 chrome has a **print** function , when I used this function to save the readme.md file as PDF, I found that all the directory in the PDF can't  jump to the correspond head .

I think the reason maybe is writing format of head . we assume the directory is the same `[overview  ](# overview )`.but the key point is the detail writing format of head \:

if we use `##overview ` to write head , the directory in PDF can't jump .But if I use `<h2 id=overview >overview  </h2>` , the directory in PDF can jump to the correspond content .

**Comment by tiimgreen** [comment]
Thanks @tonyxue 

@spartawhy117 would it be easier for you to make your own branch and use that if it's purely for making a PDF?

**Comment by spartawhy117** [comment]
@tiimgreen I will have a try
