### ISSUE TITLE
can't show all source tree

### ISSUE THREAD

**Issue by choldrim** [tiimgreen/github-cheat-sheet#142]
https://github.com/WebKit/webkit
![github webkit](https://cloud.githubusercontent.com/assets/6734555/10354885/b0b49c44-6d97-11e5-99ac-c3617cc0958d.png)

**Comment by tiimgreen** [comment]
@choldrim could you expand on what the issue is here? Not sure I understand.

**Comment by choldrim** [comment]
oh, sorry, I just saw your reply, I mean that I can not see all source, like the folder: "Source", "Tools" ...
![image](https://cloud.githubusercontent.com/assets/6734555/12045633/1e4eaa8e-aee2-11e5-92e4-12895aed7081.png)

**Comment by tiimgreen** [comment]
@choldrim I'm sorry but I don't understand what the issue is. This repo doesn't have those folders so I don't understand why you would expect to see them?

**Comment by choldrim** [comment]
@tiimgreen eh.. I don't know whether I have a problem in the last comment :(
Would you see my [screenshot](https://cloud.githubusercontent.com/assets/6734555/12045633/1e4eaa8e-aee2-11e5-92e4-12895aed7081.png) on last comment? 
And would u see this [source tree](https://github.com/WebKit/webkit/tree/master/Source) in octotree panel?

**Comment by tiimgreen** [comment]
I can see your screenshot but don't understand how this relates to GHCS. Could you list:
- steps to reproduce
- what you saw
- what you expected to see

**Comment by choldrim** [comment]
Oh, oh, I'm so sorry, I made a large mistake. I get the wrong project XD
