### ISSUE TITLE
question: rebasing the first commit

### ISSUE THREAD

**Issue by makomi** [tiimgreen/github-cheat-sheet#149]
Regarding this line from [Empty Commits](https://github.com/tiimgreen/github-cheat-sheet#empty-commits):
The first commit of a repo, as the first commit cannot be rebased later: `git commit -m "init repo" --allow-empty`.

**Question**
Can't the first commit be rebased/ modified using `git rebase --interactive --root`?

**Comment by rafalchmiel** [comment]
Yeah you're right, it can. Fixed.

**Comment by rafalchmiel** [comment]
Thanks!
