### ISSUE TITLE
Image width

### ISSUE THREAD

**Issue by szepeviktor** [tiimgreen/github-cheat-sheet#150]
Could we help image embedders?

> Images are downsized to 664 pixels width, so up to 664 px it does not get resized.

**Comment by yang-wei** [comment]
did you try using `img` tag ?

<img width="1000"  src=".." alt="..">

**Comment by szepeviktor** [comment]
<img width="1000" alt="width" src="http://dukes-lancaster.org/wp-content/uploads/2014/11/placeholder.jpg">
