### ISSUE TITLE
Refined GitHub

### ISSUE THREAD

**Issue by hkdobrev** [tiimgreen/github-cheat-sheet#156]
Does the [Refined GitHub extension](https://github.com/sindresorhus/refined-github) have a place on this cheat sheet in the GitHub section? It tries to enhance features or highlights features already available from GitHub, remove some clutter and even add some additions.

I encourage you to [read its highlights](https://github.com/sindresorhus/refined-github#highlights) and [install it](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf) to try it out.

To give some examples:
- it enhances emoji reactions by showing avatars of people
- it shows patch and diff links on commit pages (it also works arounds https://github.com/tiimgreen/github-cheat-sheet/pull/155#issuecomment-206402858)
- when using blame in GitHub it takes advantage of GitHub support for blaming parent commits with `^` and adds links to blame the parent commit

I think GitHub power users looking for more tips in the cheat sheet would find it useful.

It has a Safari port and soon it could be cross-browser with the [Web Extensions API](https://wiki.mozilla.org/WebExtensions).

**Comment by tiimgreen** [comment]
This does look like a useful tool however I don't think I should include it in the main body of the cheat sheet.

There are hundreds of tools out there that make using GitHub easier and more streamlined - I use a few myself - however I have purposefully left these out of GHCS. If I started adding everything that I thought people would find useful it would soon become a convoluted document.

For that reason I have limited everything in GHCS to Git/GitHub native functionality (I know Travis CI isn't native but I thought that was a reasonable exception to the rule).

However, I would be happy for you to create a PR adding a table at the bottom of the GitHub section with something along the lines of 'Extensions you might find useful', under the 'GitHub Resources' header.
