### ISSUE TITLE
On the pages of github there is no way to get back up from anywhere

### ISSUE THREAD

**Issue by jack17529** [tiimgreen/github-cheat-sheet#167]
On the github the pages don't offer the option to go up quickly. People get fed up from scrolling.We need a button or so on the pages to go back up. As only at the top we have other options for seeing code , issues etc.

**Comment by hatzopoulos** [comment]
In windows you can use `CTRL` + `HOME` to go to the top of the page. On Mac it's `fn` + `control` + `left arrow`.

**Comment by jack17529** [comment]
Thanks this was new for me.
