### ISSUE TITLE
Turkish Language Support

### ISSUE THREAD

**Issue by onuryurtturk** [tiimgreen/github-cheat-sheet#168]
Hi,

Can I help for supporting Turkish?

Thanks

**Comment by ad-m** [comment]
Hi,

What help do you need to prepare translation?

Greetings,

**Comment by tiimgreen** [comment]
Clone the repo, create a new file with the format README.<language>.md, translate the file then create a PR.

**Comment by onuryurtturk** [comment]
Ok, I'll prepare asap
