### ISSUE TITLE
Github shows wrong time on comments

### ISSUE THREAD

**Issue by jack17529** [tiimgreen/github-cheat-sheet#169]
It showed comment that was posted didn't match the times.

Is github time dependent on os time settings?

This can result in forgery.

**Comment by tiimgreen** [comment]
Sorry I don't understand the question.

**Comment by jack17529** [comment]
Sorry can't provide a screenshot to this,But visualise what I saw.

Sir it means that 
1. I posted a comment using ubuntu.(eg - 1hr ago)
2.You posted another comment on my comment.
3. This time I did not see your comment on ubuntu.
4.I boot for my windows.
5.Then I see your comment and the time was incorrect.(eg - 3hrs ago).
6.NOTE what happened the time of my os was wrong because of dual boot and github did not noticed and wrote wrong time on your comment.
7.But the comment that I have posted earlier still had the original right time.(eg 1hr ago)
8.Next time I will try to post a screenshot it would be funny.
9.Some people can use this as forgery.

**Comment by jack17529** [comment]
[
![image](https://cloud.githubusercontent.com/assets/15366183/23341623/051233e6-fc71-11e6-921e-79254f199fcf.png)
](url)

**Comment by jack17529** [comment]
And when I  click on the image why does it say page not found?

**Comment by hkdobrev** [comment]
@jack17529 I don't think this repository issues is the appropriate place to report bugs on GitHub. This project is about showing a lot of cool features of Git and GitHub which people may not know about. You could report problems you see on GitHub in their contact form in the footer.

**Comment by tiimgreen** [comment]
Agree with @hkdobrev if theres an issue with GitHub please report that to GitHub directly.
