### ISSUE TITLE
Github comment scroller doesn't works correctly.

### ISSUE THREAD

**Issue by jack17529** [tiimgreen/github-cheat-sheet#170]
When you drag the scroller from middle to the extreme left or right it comes back to its original position.

For example try this one - https://github.com/owtf/owtf/issues/821

The log scroller.

**Comment by jack17529** [comment]
Now it is working fine ,I don't know what happed.
Now it is working fine.
I will reopen it if I find anything suspicious.

**Comment by jack17529** [comment]
[https://drive.google.com/file/d/0B5cscCZ6VqsHSzRvRGlQc0dETzA/view?usp=sharing](url)

**Comment by tiimgreen** [comment]
As with the other issue, please report issues to GitHub directly.
