### ISSUE TITLE
Error format in aliases

### ISSUE THREAD

**Issue by chanjsq** [tiimgreen/github-cheat-sheet#187]
Format error in `git cleanup` row, aliases section. All languages are wrong.

**Comment by chanjsq** [comment]
![20_49_28__04_23_2018](https://user-images.githubusercontent.com/30150098/39127547-ebaa0e34-4737-11e8-8971-fe9f1b0d447a.jpg)

**Comment by doggy8088** [comment]
I watched the [original commit](https://github.com/tiimgreen/github-cheat-sheet/commit/4df7b84f38a3fcb9893cdc6e561e5d89f5625b32).  The content is right, only the format is wrong.

Alias: `git cleanup`
Command: `git branch --merged | grep -v '*' | xargs git branch -d`
What to Type: `git config --global alias.cleanup "!git branch --merged | grep -v '*' | xargs git branch -d"`

**Comment by doggy8088** [comment]
It's so hard to find a solutions for this kind of format.  I also create an issue here: https://github.com/github/markup/issues/1193
