### ISSUE TITLE
German translation: Question regarding the form of address ("you") 

### ISSUE THREAD

**Issue by 1coderookie** [tiimgreen/github-cheat-sheet#213]
Hi Tim,
I discovered your cheatsheet yesterday and forked it right away. Right now I started with the translation for German (if you'd like to have that language also - if not, please let me know!) but before I'm getting too deep into it - what kind of salutation / form of address should I choose? 
In English there's only the 'you', which can be either formally (e.g. talking with your boss) or more personal (e.g. talking with a friend). 
In the German language we have the formally 'sie' and the personal 'du'. 
So - which one should I choose..? 
I'd vote for the personal 'du' as it's the open source community here, but I thought I'll ask and leave that decision up to you. ;)
Cheers

**Comment by 1coderookie** [comment]
Hi again,
I started the translation using the personal form of address ("du"), but before I proceed - is this project still active or is it abandoned..?

**Comment by Merovex** [comment]
I have seen plenty of action on this in the past. It has been quiet for a few months. However, activity is community driven. Enjoy the translation!

**Comment by 1coderookie** [comment]
Ok, so I'll proceed with the translation ;) Thanks

**Comment by 1coderookie** [comment]
..closing this for now as I decided to go with the more personal form of address ("du")..
