### ISSUE TITLE
Clipboard image paste

### ISSUE THREAD

**Issue by paulirish** [tiimgreen/github-cheat-sheet#92]
I think this is a huge protip. 

* Capture screenshot (region) to clipboard (on mac: `cmd-ctrl-shift-4`) 
* Then `cmd-v` it into an issue.

![image](https://cloud.githubusercontent.com/assets/39191/5794265/39c9b65a-9f1b-11e4-9bc7-04e41f59ea5f.png)

It's actually called out from within the issue entry screen:
![image](https://cloud.githubusercontent.com/assets/39191/5794274/676ead0e-9f1b-11e4-9688-75c9f920dd75.png)

But it's so damn convenient I think it'd worth reiterating :)

**Comment by tiimgreen** [comment]
Awesome tip, thanks :+1:
